# Command: docker-compose --env-file .env.local up -d

services:
  question-db:
    hostname: "question-db"
    image: postgres:16.4
    container_name: "question-db"
    build:
      context: ./src/lib/db
    env_file:
      - ./.env.local
    volumes:
      - "question-db-docker:${PGDATA}"
      #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${EXPRESS_DB_PORT}:5432"
    restart: unless-stopped

  question-express:
    image: "question-express"
    container_name: "question-express"
    build:
      context: ./
      dockerfile: ./express.Dockerfile
      target: build
      args: 
        # For building with the correct env vars
        - env=${EXPRESS_ENV}
    ports:
      - "9002:8001"
    command: node dist/index.js
    env_file:
      - ./.env.local
    environment:
      # Docker Compose Specific
      - EXPRESS_DB_HOST=question-db
      - EXPRESS_DB_PORT=5432
    depends_on:
      - question-db
      
volumes:
  question-db-docker:
