apiVersion: v1
kind: Service
metadata:
  name: collab-db
  namespace: peerprep
  labels:
    project: peerprep
    peerprep.service: collab-db
spec:
  type: ClusterIP
  selector:
    project: peerprep
    peerprep.service: collab-db
  ports:
    - name: collab-db-5432
      port: 5432
      targetPort: collab-db-5432
