apiVersion: v1
kind: Service
metadata:
  name: chat-db
  namespace: peerprep
  labels:
    project: peerprep
    peerprep.service: chat-db
spec:
  type: ClusterIP
  selector:
    project: peerprep
    peerprep.service: chat-db
  ports:
    - name: chat-db-5432
      port: 5432
      targetPort: chat-db-5432
