apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-vol
  namespace: peerprep
  labels:
    peerprep.service: user-db
    peerprep.volume: user-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: question-db-vol
  namespace: peerprep
  labels:
    peerprep.service: question-db
    peerprep.volume: question-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collab-db-vol
  namespace: peerprep
  labels:
    peerprep.service: collab-db
    peerprep.volume: collab-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: match-db-vol
  namespace: peerprep
  labels:
    peerprep.service: match-db
    peerprep.volume: match-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
