apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: peerprep
  labels:
    project: peerprep
    peerprep.service: matching-service
spec:
  type: ClusterIP
  selector:
    project: peerprep
    peerprep.service: matching-service
  ports:
    - name: match-svc-prt
      port: 9004
      targetPort: match-svc-ctr
