apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: peerprep
  labels:
    project: peerprep
    peerprep.service: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      project: peerprep
      peerprep.service: matching-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: peerprep
        peerprep.service: matching-service
        peerprep.network.match-api: "true"
        peerprep.network.match-db: "true"
        peerprep.network.user-api: "true"
        peerprep.network.question-api: "true"
        peerprep.network.collab-api: "true"
    spec:
      initContainers:
        - name: wait-for-services
          image: redis:alpine
          env:
            - name: MATCHING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: matching-secret
                  key: MATCHING_DB_PASSWORD
            - name: MATCHING_DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: matching-secret
                  key: MATCHING_DB_PASSWORD
            - name: MATCHING_DB_HOST
              value: match-db
            - name: PEERPREP_USER_HOST
              value: http://user-service:9001
            - name: PEERPREP_QUESTION_HOST
              value: http://question-service:9002
            - name: PEERPREP_COLLAB_HOST
              value: http://collab-service:9003
          command:
            - /bin/sh
            - -c
            - |
              until REDISCLI_AUTH="$MATCHING_DB_PASSWORD" redis-cli -h "$MATCHING_DB_HOST" --user "$MATCHING_DB_USERNAME" ping; do
                echo "Waiting for Redis to be ready..."
                sleep 2
              done &
          
              until wget --no-verbose --tries=1 --spider "$PEERPREP_USER_HOST/health"; do
                echo "Waiting for User Service"
                sleep 2
              done &

              until wget --no-verbose --tries=1 --spider "$PEERPREP_QUESTION_HOST/health"; do
                echo "Waiting for Question Service"
                sleep 2
              done &

              until wget --no-verbose --tries=1 --spider "$PEERPREP_COLLAB_HOST/health"; do
                echo "Waiting for Collaboration Service"
                sleep 2
              done &

              wait
              echo "All services healthy"
      
      containers:
        - name: match-express
          image: ay2425s1cs3219g16/match-express:main
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef: 
              name: matching-secret
          env:
            - name: MATCHING_DB_HOSTNAME
              value: match-db
            - name: MATCHING_DB_PORT
              value: "6379"
            - name: PEERPREP_UI_HOST
              value: http://frontend:3000
            - name: PEERPREP_USER_HOST
              value: http://user-service:9001
            - name: PEERPREP_QUESTION_HOST
              value: http://question-service:9002
            - name: PEERPREP_COLLAB_HOST
              value: http://collab-service:9003
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - wget --no-verbose --tries=1 --spider http://localhost:9004/health || exit 1
            periodSeconds: 30
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
          ports:
            - name: match-svc-ctr
              containerPort: 9004
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
                