apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: peerprep
  labels:
    project: peerprep
    peerprep.service: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      project: peerprep
      peerprep.service: user-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: peerprep
        peerprep.service: user-service
        peerprep.network.user-api: "true"
        peerprep.network.user-db: "true"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16.4
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: EXPRESS_DB_HOST
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: EXPRESS_DB_PORT
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_USER
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_DB
          command:
            - /bin/sh
            - -c
            - |
              while ! psql -c 'SELECT 1' > /dev/null 2>&1; do
                echo "Waiting for $PGDATABASE"
                sleep 1
              done
              echo "$PGDATABASE is ready!"
      
      containers:
        - name: user-express
          # image: ay2425s1cs3219g16/user-express:main
          image: ay2425s1cs3219g16/user-express:sha-ff94455
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef: 
              name: user-secret
          env:
            - name: LOAD_TEST_POD
              value: http://user-service-load-test
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - wget --no-verbose --tries=1 --spider http://localhost:9001/health || exit 1
            periodSeconds: 30
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
          ports:
            - name: user-svc-ctr
              containerPort: 9001
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
                