apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: collab-db
  name: collab-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collab-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/code-collab-db-network: "true"
        io.kompose.service: collab-db
    spec:
      containers:
        - env:
            - name: EXPRESS_DB_HOST
              value: localhost
            - name: EXPRESS_DB_PORT
              value: "5434"
            - name: EXPRESS_ENV
              value: local
            - name: PGDATA
              value: /data/collab-db
            - name: POSTGRES_DB
              value: collaboration
            - name: POSTGRES_PASSWORD
              value: /86awM+Izo6949YgEQIls8HU+j5RlFYEInRy8auiNa8=
            - name: POSTGRES_USER
              value: peerprep-collab-express
          image: postgres:16.4
          name: collab-db
          volumeMounts:
            - mountPath: /data/collab-db
              name: collab-db-docker
      hostname: collab-db
      restartPolicy: Always
      volumes:
        - name: collab-db-docker
          persistentVolumeClaim:
            claimName: collab-db-docker
