apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: user-db-docker
  name: user-db-docker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
