services:
  postgres:
    hostname: postgres
    build:
      context: ./src/lib/db
      dockerfile: ./src/lib/db/postgres.Dockerfile
    image: "template-db"
    container_name: "template_db"
    environment:
      POSTGRES_DB: "template"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      PGDATA: "/data/template-db"
    volumes:
       - "template-db-docker:/data/template-db"
      #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"
    restart: unless-stopped

volumes:
  template-db-docker:
    external: true