name: Build & publish PeerPrep images
on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ay2425s1cs3219g16/user-express
            context: ./backend/user
            dockerfile: ./backend/user/express.Dockerfile
            build-args: |
              port=9001
          - image: ay2425s1cs3219g16/question-express
            context: ./backend/question
            dockerfile:  ./backend/question/express.Dockerfile
            build-args: |
              port=9002
          - image: ay2425s1cs3219g16/collab-express
            context: ./backend/collaboration
            dockerfile:  ./backend/collaboration/express.Dockerfile
            build-args: |
              port=9003
          - image: ay2425s1cs3219g16/match-express
            context: ./backend/matching
            dockerfile:  ./backend/matching/express.Dockerfile
            build-args: |
              port=9004
          - image: ay2425s1cs3219g16/frontend
            context: ./frontend
            dockerfile:  ./frontend/frontend.Dockerfile
            build-args: |
              port=3000
          
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker images for PeerPrep Services
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.build-args }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
