name: Build & publish PeerPrep images
on:
  [push]

env:
  DOCKERHUB_USERNAME: ay2425s1cs3219g16

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: $DOCKERHUB_USERNAME/user-express
            context: ./backend/user
            dockerfile: ./backend/user/express.Dockerfile
            build-args: |
              port=9001
          - image: $DOCKERHUB_USERNAME/question-express
            context: ./backend/question
            dockerfile:  ./backend/question/express.Dockerfile
            build-args: |
              port=9002
          - image: $DOCKERHUB_USERNAME/collab-express
            context: ./backend/collaboration
            dockerfile:  ./backend/collaboration/express.Dockerfile
            build-args: |
              port=9003
          - image: $DOCKERHUB_USERNAME/match-express
            context: ./backend/matching
            dockerfile:  ./backend/matching/express.Dockerfile
            build-args: |
              port=9004
          - image: $DOCKERHUB_USERNAME/frontend
            context: ./frontend
            dockerfile:  ./frontend/frontend.Dockerfile
            build-args: |
              port=3000
          
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker images for PeerPrep Services
        uses: docker/build-push-action@v6.9.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.build-args }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}