name: Build & publish PeerPrep images
on:
  pull_request:
    # types: [review_requested, ready_for_review]
  push:
    branches: 
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }} # Output the matrix as a JSON string
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          user:
            - 'backend/user/**'
          question:
            - 'backend/question/**'
          collaboration:
            - 'backend/collaboration/**'
          matching:
            - 'backend/matching/**'
          frontend:
            - 'frontend/**'
    - id: set-matrix
      run: |
        # Create the matrix based on the filters
        matrix=()
        if [[ "${{ steps.filter.outputs.user }}" == "true" ]]; then
          matrix+=('{
            "package": "user", 
            "image": "ay2425s1cs3219g16/user-express", 
            "context": "./backend/user", 
            "dockerfile": 
            "./backend/user/express.Dockerfile", 
            "build-args": "port=9001"
          }')
        fi
        if [[ "${{ steps.filter.outputs.question }}" == "true" ]]; then
          matrix+=('{
            "package": "question", 
            "image": "ay2425s1cs3219g16/question-express", 
            "context": "./backend/question", 
            "dockerfile": "./backend/question/express.Dockerfile", 
            "build-args": ["port=9002"]
          }')
        fi
        if [[ "${{ steps.filter.outputs.collaboration }}" == "true" ]]; then
          matrix+=('{
            "package": "collaboration", 
            "image": "ay2425s1cs3219g16/collab-express", 
            "context": "./backend/collaboration", 
            "dockerfile": "./backend/collaboration/express.Dockerfile", 
            "build-args": ["port=9003"]
          }')
        fi
        if [[ "${{ steps.filter.outputs.matching }}" == "true" ]]; then
          matrix+=('{
            "package": "matching", 
            "image": "ay2425s1cs3219g16/match-express", 
            "context": "./backend/matching", 
            "dockerfile": "./backend/matching/express.Dockerfile", 
            "build-args": ["port=9004"]
          }')
        fi
        if [[ "${{ steps.filter.outputs.frontend }}" == "true" ]]; then
          matrix+=('{
            "package": "frontend", 
            "image": "ay2425s1cs3219g16/frontend", 
            "context": "./frontend", 
            "dockerfile": "./frontend/frontend.Dockerfile", 
            "build-args": ["port=3000"]
          }')
        fi
        formatted_matrix=$(echo "[${matrix[*]}]" | jq -c .)
        echo "matrix=$formatted_matrix" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: changes
    if: ${{ fromJson(needs.changes.outputs.matrix)[0] != null }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.changes.outputs.matrix) }} # Use the matrix from the first job
          # - package: user
          #   image: ay2425s1cs3219g16/user-express
          #   context: ./backend/user
          #   dockerfile: ./backend/user/express.Dockerfile
          #   build-args: |
          #     port=9001
          # - package: question
          #   image: ay2425s1cs3219g16/question-express
          #   context: ./backend/question
          #   dockerfile:  ./backend/question/express.Dockerfile
          #   build-args: |
          #     port=9002
          # - package: collaboration
          #   image: ay2425s1cs3219g16/collab-express
          #   context: ./backend/collaboration
          #   dockerfile:  ./backend/collaboration/express.Dockerfile
          #   build-args: |
          #     port=9003
          # - package: matching
          #   image: ay2425s1cs3219g16/match-express
          #   context: ./backend/matching
          #   dockerfile:  ./backend/matching/express.Dockerfile
          #   build-args: |
          #     port=9004
          # - package: frontend
          #   image: ay2425s1cs3219g16/frontend
          #   context: ./frontend
          #   dockerfile:  ./frontend/frontend.Dockerfile
          #   build-args: |
          #     port=3000
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker images for PeerPrep Services
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.build-args }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
